{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "predictmaint.fullname" . }}
  labels:
    {{- include "predictmaint.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "predictmaint.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        {{- toYaml .Values.networkPolicy.ingressFrom | nindent 8 }}
      ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
    - from:
        {{- toYaml .Values.networkPolicy.metricsFrom | nindent 8 }}
      ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
{{- end }}
